# This example requires CocoaPods 1.0

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

# temp hack
source 'https://github.com/brion/OGVKit-Specs.git'

target 'OGVKit Example' do
  pod "OGVKit", :path => "../"

  target 'OGVKit Tests' do
    inherit! :search_paths
  end
end
